version: 2.1

env_defaults: &env_defaults
  executor: node

executors:
  node:
    parameters:
      tag:
        type: string
        default: '12.18'
    docker:
      - image: cimg/node:<<parameters.tag>>

jobs:
  prepare:
    <<: *env_defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ arch }}-{{ checksum "package-lock.json" }}
            - node-deps-{{ arch }}-
            - node-deps-
      - run: npm install
      - save_cache:
          key: node-deps-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - .npm
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .npm
            - node_modules

  lint:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run lint

  build:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - store_artifacts:
          path: .next
          destination: build

workflows:
  lint_and_build:
    jobs:
      - prepare
      - lint:
          requires:
                - prepare
      - build:
          requires:
                - prepare
                - lint
