name: Kwenta CI

on:
  push:
  pull_request:
    branches: [master, dev, v2, v2-dev]

jobs:
  audit:
    # run only on master/dev/v2/v2-dev branch and pull requests
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/v2-dev'
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/synthetixio/docker-sec-tools/base:16.14
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}
      options: --shm-size=7gb

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

      - name: Audit dependencies
        run: npm audit --audit-level=critical

      - name: Lockfile lint
        run: lockfile-lint -p package-lock.json --type npm --allowed-hosts npm github.com --allowed-schemes "https:" "git+ssh:" "npm:"

  lint:
    needs: audit
    # run only on audit success or audit skipped
    if: always() && (needs.audit.result == 'success' || needs.audit.result == 'skipped')
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=8192

    container:
      image: ghcr.io/synthetixio/docker-node/ubuntu:16.14
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}
      options: --shm-size=7gb

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

      - name: Set npm cache directory
        run: npm config set cache .npm-cache --global
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # pin@v2
        with:
          path: |
            .npm-cache
            node_modules
          key: ${{ runner.os }}-ubuntu-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ubuntu-node-
        continue-on-error: true

      # fix: permission issues on ghactions+docker+npm@8
      - name: Chown workspace
        run: chown -R $(whoami) .

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit --legacy-peer-deps --optimize_for_size

      - name: Lint
        # run only on master/dev/v2/v2-dev branch and pull requests
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/v2-dev'
        run: npm run lint:sarif

      - name: Upload lint results
        # run if lint failed and only on master/dev/v2/v2-dev branch and pull requests
        if: always() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/v2-dev')
        uses: github/codeql-action/upload-sarif@33f3438c1d59883f5e769fdf2b6adb6794d91d0f # pin@codeql-bundle-20210517
        with:
          sarif_file: lint-results.sarif
        continue-on-error: true

      - name: Unit tests
        # run only on master/dev/v2/v2-dev branch and pull requests
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/v2-dev'
        run: npm run test:unit

  build:
    needs: lint
    # run only on lint success or lint skipped
    if: always() && (needs.lint.result == 'success' || needs.lint.result == 'skipped')
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=8192

    container:
      image: ghcr.io/synthetixio/docker-node/ubuntu:16.14
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}
      options: --shm-size=7gb

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

      - name: Set npm cache directory
        run: npm config set cache .npm-cache --global
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # pin@v2
        with:
          path: |
            .npm-cache
            node_modules
          key: ${{ runner.os }}-ubuntu-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ubuntu-node-
        continue-on-error: true

      # fix: permission issues on ghactions+docker+npm@8
      - name: Chown workspace
        run: chown -R $(whoami) .

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit --legacy-peer-deps --optimize_for_size

      - name: Cache next.js build cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # pin@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-next.js-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-next.js-cache-
        continue-on-error: true

      - name: Build
        run: npm run build --optimize_for_size

      - name: Compress build
        run: tar -zcvf build.tar.gz .next

      - name: Archive build
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/v2-dev'
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # pin@v2
        with:
          name: build
          path: build.tar.gz
